### PR TITLE
configlet-ci: use track's fetch-configlet script

### PR DESCRIPTION
**Pull request by ee7**
(Untested).

Can we do something like this?

Refs: #101 (maybe closes?)
Closes: #103

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
No idea. We'll have to test. Also, I think this won't have the GITHUB_TOKEN value available in the script.

**Comment by ErikSchierboom** [comment]
Yes, that works, but I'd be most interested in whether it use the github_token (I expect it doesn't). Could you test that?

**Comment by SaschaMann** [comment]
It was intentionally not meant to use the track's `fetch-configlet` script for stability and simplicity (no need for all the OS handling if the environment is known). Once it can be ensured that the track's script is always up-to-date, this would be a low-risk change, but that's not the case yet.

**Comment by ErikSchierboom** [comment]
@SaschaMann It is guaranteed to be present: https://github.com/exercism/org-wide-files/blob/main/tracks-files/bin/fetch-configlet

**Pull request closed without merging**
