### PR TITLE
configlet-ci: Check JSON files are valid

### PR DESCRIPTION
**Pull request by ee7**
See https://github.com/exercism/wren/pull/26#pullrequestreview-674121102

To-do:
- [ ] Print the path to the file with an error
- [ ] Add the check in a separate job?
- [ ] Find a way to produce an error for a duplicate key?

Note that this does not currently produce an error for a duplicate key. But it does for:
- a comment with `#`
- a trailing comma

### CODE REVIEW

**Comment by ee7** [comment]
Actually: I've thought of a better way.

I'll make a PR to `configlet` such that `configlet lint` runs `jq` (or potentially a stricter JSON validator) during CI.

**Comment by joshgoebel** [comment]
This PR would still be valid as not everyone is guaranteed to have `jq` installed (as you pointed out previously)

**Comment by ee7** [comment]
> This PR would still be valid as not everyone is guaranteed to have `jq` (or stricter validator?) installed (as you pointed out previously)...

I don't think so: if `configlet lint` ran `jq`, then it would do so in CI (and the GitHub Actions environments have `jq` installed). This PR would be redundant, right?

But it's a moot point: it turned out that it was easier to just patch the too-lenient-for-us part of the Nim JSON parser than to go via `jq` anyway. And that doesn't require/prefer the user to have `jq` installed, or special-case running in CI. 

Should be in the next configlet release.

**Comment by ErikSchierboom** [comment]
> But it's a moot point: it turned out that it was easier to just tweak the too-lenient part of the Nim JSON parser (this was my original plan) than to go via jq anyway. And that doesn't require/prefer the user to have jq installed, or special-case running in CI.

What, you fixed it! That's great.

**Comment by joshgoebel** [comment]
Great news indeed!

**Pull request closed without merging**
